### ISSUE TITLE
Broken links in Anchor

### ISSUE THREAD

**Issue by jeremyzilar** [GSA/touchpoints-site#14]
There are a few broken links with the "Anchor" on the site
https://demo.touchpoints.digital.gov/

This can be easily fixed to use the language and link on the Digital.gov anchor https://digital.gov/

![image](https://user-images.githubusercontent.com/395641/72180300-dc37dd80-33b4-11ea-81f4-cf6250b6283c.png)

**Comment by afomi** [comment]
@jeremyzilar - https://github.com/GSA/touchpoints-site/pull/15

**Comment by afomi** [comment]
resolved in #15
