### ISSUE TITLE
Touchpoints app homepage: copy edits

### ISSUE THREAD

**Issue by ToniBonittoGSA** [GSA/touchpoints-site#19]
For https://touchpoints.app.cloud.gov/ 

1) In the Welcome section:

> Welcome to Touchpoints
> A Touchpoint is the interaction point between a **Customer** and **Service Provider**.
> 
> Touchpoints exists to help **Federal Agencies**:
> 
> - Administer the A-11 **Form**
> - Streamline CX CAP Goal reporting
> - Solicit open-ended **Feedback**
> - Recruit users to talk to during product and service development

- [x] I made seven words above bold; these should not be capitalized.  
- [x] We can't assume everyone knows acronyms; use: `customer experience (CX) CAP Goal`
- [x] Is it A-11 or A11? There is inconsistent use of both on this older Touchpoints page https://feedback.usa.gov/faq/ 
- [x] are links needed for the `A-11 form` and/or `customer experience CX CAP Goal` (https://www.performance.gov/CAP/cx/)?

**Comment by ToniBonittoGSA** [comment]
2) In the **Sign up** section

> Any Federal employee with a .gov email address can use Touchpoints. Your account will be automatically created the first time you sign in.

- [ ] change `Federal` to `federal`. 
- [ ] Specifying only federal .gov email addresses leaves out federal .mil accounts and other [rare] federal domains. Is this service not for those folks?

**Comment by ToniBonittoGSA** [comment]
3) In the **Log in** section

> Touchpoints uses Login.gov to handle user accounts. Once you authenticate with Login.gov you will be signed in and redirected back to Touchpoints.

- [ ] add a comma in second sentence: `Once you authenticate with Login.gov, you will be signed in and redirected back to Touchpoints.`

**Comment by afomi** [comment]
thanks @ToniBonittoGSA!

1. the capitalizations have been taken care of
1. customer experience (CX) was added
1. it should be a-11, and a PR was cut for the other site too, for consistency
1. no links needed for now

Sign Up section

1. federal has been changed
1. a note has been added for .mil too. anything more rare, we can have a discussion

Log In Section

1. comma has been added.

Viewable at https://touchpoints-staging.app.cloud.gov/

**Comment by ToniBonittoGSA** [comment]
4) In the footer section

> Terms of Service
> Get help for customer issues
> Built and maintained by OPP

- [ ] Links to document files (a PDF is used for the Terms of Service) need to convey to the user that they are about to open or download a file. This is normally done by adding that info in parentheses, like: [OMB M-17-06, Policies for Federal Agency Public Websites and Digital Services (PDF, 1.2 MB, 18 pages, November 2016)](https://www.whitehouse.gov/sites/whitehouse.gov/files/omb/memoranda/2017/m-17-06.pdf). **Suggestion**: put the copy in a web page that clearly indicates when the Terms were last updated.

- [ ] Email links should be stated as such with related call-to-action text. "Get help for customer issues" sounds like it'll go to a help/support page. **Suggested text**: Email us for customer support

- [ ] Change `OPP` to `TTS Solutions` and update the link to: https://www.gsa.gov/about-us/organization/federal-acquisition-service/technology-transformation-services/tts-solutions

**Comment by ToniBonittoGSA** [comment]
5) Top navigation bar -- `Support` link

Navigation is for pages, not email links. 
**Suggestion**: create a _Contact Us_ page and change wording in nav (preferred), or just remove Support from nav since an email link is in the footer

**Comment by ToniBonittoGSA** [comment]
Hi @afomi -- was in a meeting; here are 2 more.

**Comment by afomi** [comment]
@ToniBonittoGSA - 2/3 items in #4 were addressed. And 5 has been addressed. 

I created https://github.com/GSA/touchpoints-site/issues/20 to track the Terms page that needs to be created.

**Comment by afomi** [comment]
all addressed for now
